import { Client } from '../../types/clients';

// Realistic-looking seed scattered across LA so the Atlas map looks alive.
// Coordinates are real LA-area lat/lng so the bbox auto-fit gives a nice view.
export const seedClients: Client[] = [
  {
    id: 'c-techflow',
    name: 'TechFlow Solutions',
    industry: 'SaaS / DevTools',
    website: 'https://techflow.com',
    location: 'Downtown LA',
    lat: 34.0407, lng: -118.2468,
    stage: 'partner',
    tier: 'platinum',
    risk: 'healthy',
    healthScore: 92,
    bookmarked: true,
    primaryContact: {
      name: 'Sarah Johnson',
      role: 'Partnership Director',
      email: 'sarah@techflow.com',
      phone: '+1 (555) 123-4567',
      linkedin: 'linkedin.com/in/sarahjohnson',
    },
    mrr: 25000,
    totalValue: 450000,
    contractStart: new Date('2024-01-15'),
    contractEnd: new Date('2026-01-15'),
    tags: ['Strategic', 'Enterprise'],
    notes: 'Anchor partner. Q4 review went well; expanding to two new verticals in 2026.',
    touches: [
      { id: 't1', type: 'meeting', body: 'Q4 business review — positive', at: new Date('2024-12-20') },
      { id: 't2', type: 'email',   body: 'Sent 2026 roadmap deck', at: new Date('2024-11-10') },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-20'),
    lastContactAt: new Date('2024-12-20'),
  },
  {
    id: 'c-global',
    name: 'Global Innovations',
    industry: 'Healthcare',
    website: 'https://global-innovations.com',
    location: 'Santa Monica',
    lat: 34.0195, lng: -118.4912,
    stage: 'partner',
    tier: 'gold',
    risk: 'healthy',
    healthScore: 84,
    bookmarked: false,
    primaryContact: {
      name: 'Michael Chen',
      role: 'VP Partnerships',
      email: 'michael@global-innovations.com',
      phone: '+1 (555) 987-6543',
    },
    mrr: 18000,
    totalValue: 350000,
    contractStart: new Date('2024-03-10'),
    contractEnd: new Date('2027-03-10'),
    tags: ['Healthcare', 'Telemedicine'],
    notes: 'Integration sandbox active. Production rollout slipped to Q2.',
    touches: [
      { id: 't1', type: 'email', body: 'QBR scheduled for Q1', at: new Date('2024-12-18') },
    ],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-12-18'),
    lastContactAt: new Date('2024-12-18'),
  },
  {
    id: 'c-premium-auto',
    name: 'Premium Auto Detailing',
    industry: 'Car Detailing',
    location: 'Downtown LA',
    lat: 34.0522, lng: -118.2437,
    reviewCount: 127,
    mapsUrl: 'https://maps.google.com',
    stage: 'active',
    tier: 'silver',
    risk: 'healthy',
    healthScore: 78,
    bookmarked: false,
    primaryContact: { name: 'Mike Alvarez', email: 'mike@premiumauto.com', phone: '+1 (555) 222-1111' },
    mrr: 1200, totalValue: 14400,
    contractStart: new Date('2025-09-01'),
    contractEnd: new Date('2026-09-01'),
    tags: ['Local', 'Retention'],
    notes: 'Renewed annual plan. Wants social-content add-on.',
    touches: [{ id: 't1', type: 'call', body: 'Renewal call — locked', at: new Date('2025-09-01') }],
    createdAt: new Date('2025-02-12'),
    updatedAt: new Date('2025-09-01'),
    lastContactAt: new Date('2025-09-01'),
  },
  {
    id: 'c-elite-wash',
    name: 'Elite Car Wash',
    industry: 'Car Detailing',
    location: 'Beverly Hills',
    lat: 34.0736, lng: -118.4004,
    reviewCount: 89,
    mapsUrl: 'https://maps.google.com',
    stage: 'outreach',
    tier: 'lead',
    risk: 'watch',
    healthScore: 50,
    bookmarked: false,
    primaryContact: { name: 'Sarah Lin', email: 'sarah@elitecarwash.com' },
    mrr: 0, totalValue: 0,
    tags: ['Cold'],
    notes: 'Left voicemail twice. Try IG DM next.',
    touches: [{ id: 't1', type: 'call', body: 'Voicemail — no callback', at: new Date('2025-10-05') }],
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-10-05'),
    lastContactAt: new Date('2025-10-05'),
  },
  {
    id: 'c-golden-fork',
    name: 'The Golden Fork',
    industry: 'Restaurant',
    location: 'Santa Monica',
    lat: 34.0211, lng: -118.4814,
    reviewCount: 245,
    mapsUrl: 'https://maps.google.com',
    stage: 'engaged',
    tier: 'lead',
    risk: 'healthy',
    healthScore: 72,
    bookmarked: true,
    primaryContact: { name: 'Marco Bellini', email: 'marco@goldenfork.com', phone: '+1 (555) 444-9988' },
    mrr: 0, totalValue: 0,
    tags: ['Hot', 'Reply'],
    notes: 'Replied positively. Wants pricing for 3 locations.',
    touches: [{ id: 't1', type: 'email', body: 'Sent pricing PDF', at: new Date('2025-11-02') }],
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-11-02'),
    lastContactAt: new Date('2025-11-02'),
  },
  {
    id: 'c-fitzone',
    name: 'FitZone Gym',
    industry: 'Fitness',
    location: 'West Hollywood',
    lat: 34.0900, lng: -118.3617,
    reviewCount: 98,
    mapsUrl: 'https://maps.google.com',
    stage: 'discovery',
    tier: 'lead',
    risk: 'watch',
    healthScore: 40,
    bookmarked: false,
    primaryContact: { name: 'Jen Park' },
    mrr: 0, totalValue: 0,
    tags: ['Untouched'],
    notes: '',
    touches: [],
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2025-11-20'),
  },
  {
    id: 'c-cafe-luna',
    name: 'Cafe Luna',
    industry: 'Restaurant',
    location: 'Venice Beach',
    lat: 34.0118, lng: -118.4951,
    reviewCount: 156,
    mapsUrl: 'https://maps.google.com',
    stage: 'active',
    tier: 'bronze',
    risk: 'healthy',
    healthScore: 81,
    bookmarked: false,
    primaryContact: { name: 'Antonio Rossi', email: 'antonio@cafeluna.com', phone: '+1 (555) 314-2299' },
    mrr: 900, totalValue: 6300,
    contractStart: new Date('2025-06-01'),
    contractEnd: new Date('2026-06-01'),
    tags: ['Local'],
    notes: 'Loves the product. Asked about referral commission.',
    touches: [{ id: 't1', type: 'meeting', body: 'Coffee chat in-person', at: new Date('2025-11-18') }],
    createdAt: new Date('2025-05-20'),
    updatedAt: new Date('2025-11-18'),
    lastContactAt: new Date('2025-11-18'),
  },
  {
    id: 'c-nova-realty',
    name: 'Nova Realty Group',
    industry: 'Real Estate',
    location: 'Hollywood',
    lat: 34.0928, lng: -118.3287,
    reviewCount: 64,
    stage: 'dormant',
    tier: 'lead',
    risk: 'at-risk',
    healthScore: 32,
    bookmarked: false,
    primaryContact: { name: 'Dana White', email: 'dana@novarealty.com' },
    mrr: 0, totalValue: 0,
    tags: ['Re-engage'],
    notes: 'Was interested in Q2, then went silent. Worth a Q1 ping.',
    touches: [{ id: 't1', type: 'email', body: 'Initial outreach — no reply', at: new Date('2025-05-08') }],
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2025-05-08'),
    lastContactAt: new Date('2025-05-08'),
  },
  {
    id: 'c-northbeam',
    name: 'Northbeam Analytics',
    industry: 'Analytics',
    website: 'https://northbeam.io',
    location: 'Culver City',
    lat: 34.0211, lng: -118.3965,
    stage: 'active',
    tier: 'gold',
    risk: 'at-risk',
    healthScore: 48,
    bookmarked: true,
    primaryContact: { name: 'Priya Shah', role: 'Head of Ops', email: 'priya@northbeam.io' },
    mrr: 7800, totalValue: 62400,
    contractStart: new Date('2024-08-01'),
    contractEnd: new Date('2026-02-01'),
    tags: ['Renewal soon', 'High value'],
    notes: 'Renewal in 90 days. Usage dropped 30% last month. Schedule QBR.',
    touches: [{ id: 't1', type: 'call', body: 'Heard rumours of vendor review', at: new Date('2025-11-25') }],
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2025-11-25'),
    lastContactAt: new Date('2025-11-25'),
  },
  {
    id: 'c-harbor-legal',
    name: 'Harbor Legal',
    industry: 'Legal',
    location: 'Long Beach',
    lat: 33.7701, lng: -118.1937,
    stage: 'churned',
    tier: 'silver',
    risk: 'critical',
    healthScore: 10,
    bookmarked: false,
    primaryContact: { name: 'Lila Ortega' },
    mrr: 0, totalValue: 4200,
    contractStart: new Date('2024-03-01'),
    contractEnd: new Date('2024-12-01'),
    tags: ['Churned', 'Postmortem'],
    notes: 'Did not renew. Cited budget cuts. Try win-back in 6 months.',
    touches: [{ id: 't1', type: 'stage-change', body: 'Marked churned', at: new Date('2024-12-01') }],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-12-01'),
    lastContactAt: new Date('2024-12-01'),
  },
  {
    id: 'c-orbital',
    name: 'Orbital Fitness',
    industry: 'Fitness',
    location: 'Pasadena',
    lat: 34.1478, lng: -118.1445,
    reviewCount: 212,
    stage: 'engaged',
    tier: 'lead',
    risk: 'healthy',
    healthScore: 66,
    bookmarked: false,
    primaryContact: { name: 'Rico Mendes', email: 'rico@orbitalfit.com' },
    mrr: 0, totalValue: 0,
    tags: ['Demo booked'],
    notes: 'Demo set for next Tuesday at 2pm.',
    touches: [{ id: 't1', type: 'meeting', body: 'Demo scheduled', at: new Date('2025-12-01') }],
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-12-01'),
    lastContactAt: new Date('2025-12-01'),
  },
  {
    id: 'c-saltline',
    name: 'Saltline Surf Co.',
    industry: 'Retail',
    location: 'Manhattan Beach',
    lat: 33.8847, lng: -118.4109,
    reviewCount: 187,
    stage: 'outreach',
    tier: 'lead',
    risk: 'watch',
    healthScore: 55,
    bookmarked: false,
    primaryContact: { name: 'Coral Reyes', email: 'hello@saltline.co' },
    mrr: 0, totalValue: 0,
    tags: ['IG sent'],
    notes: 'Sent Instagram DM with portfolio links.',
    touches: [{ id: 't1', type: 'whatsapp', body: 'IG DM sent', at: new Date('2025-11-28') }],
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2025-11-28'),
    lastContactAt: new Date('2025-11-28'),
  },
];
